dwa_local_planner:
  ros__parameters:
    max_vel_x: 0.5
    max_vel_theta: 0.5
    vx_samples: 10
    vtheta_samples: 20
    acc_lim_x: 1.0
    acc_lim_theta: 1.0
    path_topic: "/global_path"
    odom_topic: "/odom"
    cmd_vel_topic: "/cmd_vel"
    local_costmap_topic: "/local_costmap"
    goal_tolerance: 0.1
    local_costmap_frame: "local_costmap"
    safe_distance: 0.5
    heading_coefficient: 1.0
    distance_coefficient: 1.0
    velocity_coefficient: 1.0
    dt: 0.1
    steps: 10
    target_select_point: 5