dwa_main:
  ros__parameters:
    grid_topic: /local_costmap
    path_topic: /dstar_plan
    cmd_vel_topic: /cmd_vel_nav
    robot_frame: base_link
    static_frame: map
    max_axis_speed: 0.5
    min_axis_speed: -0.5
    axis_speed_resolution: 0.1
    min_omega_speed: -0.8
    max_omega_speed: 0.8
    omega_speed_resolution: 0.1
    dt: 0.1
    sample_time: 1.0